### ISSUE TITLE
Anyone can share the SDK file?

### ISSUE THREAD

**Issue by koolou** [dimensional-de/napi-canon-cameras#26]
I couldn't find a downloadable SDK Link(EDSDK 13.18.30). 
Could any kind soul share it? 

Thanks a lot!!!

**Comment by thisoverride** [comment]
> I couldn't find a downloadable SDK Link(EDSDK 13.18.30). Could any kind soul share it?
> 
> Thanks a lot!!!

Hello Koolou you can find all version of ESDK on developers.canon you juste need create a account and go to resource

**Comment by ThomasWeinert** [comment]
No, you have to get it from Canon. Canon does not allow others to distribute the full SDK.
