### ISSUE TITLE
ForLabel in aperture & shutter-speed sometimes returns inaccurate data for values affected by Custom Function (marked with '1/3')

### ISSUE THREAD

**Issue by SamsonSmithC** [dimensional-de/napi-canon-cameras#9]
The ForLabel function in aperture.cc & shutter-speed.cc returns the first value that matches the label. Entries affected by the 'Exposure Level Increment' custom function all have 2 values mapped to the same label in no particular order. The means switching the Exposure Level Increment between 1/2 and 1/3, won't solve the issue, just change which values are wrong. Some values returned by this function will always be incorrect unless it references the camera's Exposure Level Increment to choose between the duplicate mappings.

Exposure Level Increment:
Property ID: 9
Specifier: 257
Values:
 - 0: (1/3-stop)
 - 1: (1/2-stop)

**Comment by ThomasWeinert** [comment]
Merged: https://github.com/dimensional-de/napi-canon-cameras/pull/10
